### ISSUE TITLE
book animation

### ISSUE THREAD

**Issue by tgkprog** [PacktPublishing/Learning-LibGDX-Game-Development-Second-Edition#2]
the game on play store has a nice spinning animation of the book, on the menu screen. Can you please add that here? Thank you

**Comment by techsachinkumar** [comment]
Hi,

Could you give us more clarity about the game on Playstore so that we can solve your problem.

Regards.

**Comment by Raith** [comment]
https://play.google.com/store/apps/details?id=com.gamerald.canyonbunny

@techsachinkumar, how arent you aware of this? :D I haven't installed it, so I do not know what books spinning anmation @tgkprog is talking about, but without a doubt he means Canyon Bunny, which this is a repo for, on google play.
